<%@ Page Title="Introduction" Language="VB" AutoEventWireup="false" CodeFile="052.aspx.vb" Inherits="_052" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
<div class="sixcol editorcontent" id="spaltemitte">
                  <div class="content">
                     <h1>
                        Introduction
                     </h1><!-- Indexüberschrift:  -->
                     <p>
						The aim of the Japanese-German Research Unit "Advanced spintronic materials and transport phenomena (ASPIMATT)" was and continous to further develop the foundations for a future spintronics. Key is to use the spin degree of freedom as carrier of information. In the recent years spintronics has become a wide research field addressed worldwide. First outcomes, such as magnetic sensors based on the giant magnetoresistance and the tunneling magnetoresistance effect have revolutionized the hard-disc industries; novel developments such as spin-transfer- torque random access memory are currently aiming at the market.
					 </p>
                     <p>
                        Key to this field is the development of largely improved magnetic materials and their tailoring to spintronic applications, and this is the central focus of the ASPIMATT research unit. The groups collaborating in ASPIMATT have recognized the need for new materials, and they have opened the new field of the material class of Heusler compounds for spintronic applications. Major contributions to spintronics from the ASPIMATT team have been the development of tetragonal Heusler compounds for spin-transfer torque applications, nowadays used by many other groups as well as industry, high-quality devices for current-perpendicular-plane (CPP) GMR applications with record magneto-resistive parameters, especially for the next-generation read heads in hard- disk industries, and, recently, innovative lateral spin transport devices. In the first funding period we have developed and characterized new spintronic materials for applications at room temperature and the fabrication of prototype devices. Now, in the second funding period, as foreseen in the long-term goals, we change the focus more in direction of the study of new devices for spin transport phenomena, in particular lateral spin current phenomena and phenomena related to spin orbit coupling. A novel development in the field is the consideration of effects depending on thermal gradients – spin-caloric effects – and this is now taken up by a specific new project.
                     </p>
					 
<!-- The aim of the proposed Japanese-German Research Unit “Advanced spintronic materials and transport phenomena (ASPIMATT)” is to develop the foundations for a future spintronics with the potential to complement and succeed conventional CMOS. The specific approach lies on the development and characterization of new spintronic materials for applications at room temperature and on the study of new spin transport phenomena, in particular lateral spin current phenomena. The research subject lies in the field of nanoelectronics, specifically in the research area “Nanospintronics and related materials and structures”. Many problems in the field of spintronics still lack good solutions, although there is very high pressure from the market side. The concept of half-metallic Heusler compounds provides a perspective for novel solutions. Heusler compounds can be designed and made with high spin polarization and high Curie temperature, as well as, depending on the application, high spin injection efficiency, very low or high damping, tunable magnetic moment (low and high magnetic moment can be realized), and tunable anisotropy. Thus, there is very high potential, that many material related problems, present in current-day 3d metal systems, can be overcome. A big challenge is still the handling of interfaces with respect to their chemical (atomic diffusion and roughness), electronic (e.g., Schottky barrier design) and spin properties (spin injection and spin pumping). In addition potential for new phenomena and applications exists using novel materials in the Heusler compound family, to name here novel semi-conducting Heusler compounds to be used as non-ferromagnetic spin conductors.<br />
        To achieve this highly ambitious aim, the needed thorough experience and expertise is not localized in a single place and not even in a single country, and thus groups from two German universities, the Johannes Gutenberg Universität Mainz and the Technische Universität Kaiserslautern, combine their expertise with groups at the Tohoku University, Sendai, Japan. We feel we have a working unique expertise in understanding and making Heusler compounds as the only consortium in this field worldwide, which covers the full range from the computer based design to applications in real devices.
-->
                  </div>
               </div>               
</asp:Content>